package app.syncler.core.crypto

import javax.crypto.Cipher
import javax.crypto.spec.GCMParameterSpec
import javax.crypto.spec.SecretKeySpec
import org.junit.Assert.assertArrayEquals
import org.junit.Assert.assertEquals
import org.junit.Assert.assertNotNull
import org.junit.Test

/**
 * Phase 9b HPKE cross-platform vector. The bytes below were
 * generated by the server-side PyCA implementation
 * (`server/app/crypto/hpke.py`); Android MUST recover the same
 * CEK and payload using BC's HPKE primitives. If this test
 * fails, the cross-platform invariant is broken and senders'
 * messages won't decrypt on Android.
 */
class HpkeTest {

    @Test
    fun crossPlatformVector_opens_cek_and_decrypts_payload() {
        val sk = hexBytes("0001020304050607080910111213141516171819202122232425262728293031")
        val pk = hexBytes("c1e0c8f5681ecdbdfeed4aaa5499ce9754d0f4719a9e0c1781cd78fed23da714")
        val expectedCek = hexBytes("11".repeat(32))
        val info = hexBytes(
            "7b226465766963655f6964223a2234343434343434342d343434342d343434342d343434342d343434343434343434343434222c22656e76656c6f70655f6b696e64223a226576656e74222c22657870697265735f6174223a22323032362d30362d30315430303a30303a30305a222c226d696e5f706c7567696e5f76657273696f6e223a22222c227061796c6f61645f636970686572746578745f736861323536223a2232336639633435366439353035643337373339653233353865326638306362353534396264363866303332616131663737613334663831336137303233383531222c227061796c6f61645f6e6f6e6365223a2241414141414141414141414141414141222c22706c7567696e5f6964223a2233333333333333332d333333332d333333332d333333332d333333333333333333333333222c2270726f746f636f6c5f76657273696f6e223a322c2273656e6465725f6964223a2231313131313131312d313131312d313131312d313131312d313131313131313131313131222c22757365725f6964223a2232323232323232322d323232322d323232322d323232322d323232323232323232323232227d"
        )
        val hpkeKemOutput = hexBytes("11d2932fa315ed4aecc98b8d7cc3a6fc71e486305ffb2c032d9ff5bc7969fc4e")
        val hpkeCiphertext = hexBytes("dc0026d224313589a5cdd3210e49270c34a39631fa6143e0fcb0dac3819f5ae265b88683b834861c152fa78924158a4d")
        val payloadCiphertext = hexBytes("acaf720b8e8ffeeb6e69ce28ab9ebbfb970ffdf36e354a2cf8f67cf550df066c39c8648e")
        val payloadAad = hexBytes(
            "7b22656e76656c6f70655f6b696e64223a226576656e74222c22657870697265735f6174223a22323032362d30362d30315430303a30303a30305a222c226d696e5f706c7567696e5f76657273696f6e223a22222c22706c7567696e5f6964223a2233333333333333332d333333332d333333332d333333332d333333333333333333333333222c2270726f746f636f6c5f76657273696f6e223a322c2273656e6465725f6964223a2231313131313131312d313131312d313131312d313131312d313131313131313131313131222c22757365725f6964223a2232323232323232322d323232322d323232322d323232322d323232323232323232323232227d"
        )
        val payloadNonce = ByteArray(12) // all zeros

        val recoveredCek = Hpke.openCekForDevice(
            privateKeyRaw = sk,
            hpkeKemOutput = hpkeKemOutput,
            hpkeCiphertext = hpkeCiphertext,
            info = info,
        )
        assertArrayEquals(
            "Recovered CEK must equal the sender-side CEK",
            expectedCek, recoveredCek,
        )

        // AES-256-GCM decrypt the payload using the recovered CEK +
        // payload_nonce + payload_aad.
        val cipher = Cipher.getInstance("AES/GCM/NoPadding")
        cipher.init(
            Cipher.DECRYPT_MODE,
            SecretKeySpec(recoveredCek, "AES"),
            GCMParameterSpec(128, payloadNonce),
        )
        cipher.updateAAD(payloadAad)
        val plaintext = cipher.doFinal(payloadCiphertext)
        assertArrayEquals(
            "Payload plaintext must match the sender's input",
            "hello cross-platform".toByteArray(Charsets.UTF_8), plaintext,
        )
    }

    @Test
    fun generateKeypair_returns_32_byte_components() {
        val (sk, pk) = Hpke.generateX25519Keypair()
        assertEquals(32, sk.size)
        assertEquals(32, pk.size)
    }

    @Test
    fun sha256Hex_is_lowercase_64_chars() {
        val digest = Hpke.sha256Hex("".toByteArray())
        assertEquals(64, digest.length)
        assertEquals(digest, digest.lowercase())
        assertEquals("e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855", digest)
    }

    private fun hexBytes(hex: String): ByteArray {
        require(hex.length % 2 == 0) { "hex length must be even" }
        return ByteArray(hex.length / 2) { i ->
            hex.substring(i * 2, i * 2 + 2).toInt(16).toByte()
        }
    }
}
